name: Malloy love You
description: |
  This is a website where will Malloy is welcomeing you.
version: 1.0
category: "Web service"
maintainer: "pinyo"
license: "really free"
projectURL: "no have URL"

